### ISSUE TITLE
Getting Error while selecting images for upload 

### ISSUE THREAD

**Issue by siripravi** [luyadev/luya-module-gallery#9]
### What steps will reproduce the problem?
 In ActiveWindow popup, clicking the checkbox against to an image for selection, giving an eror.

### What is the expected result?
The selected image should be added to the existing album.

### What do you get instead? (A Screenshot can help us a lot!)

Error: Call to a member function toArray() on bool in C:\luyashopadmin\vendor\luyadev\luya-module-admin\src\aws\ImageSelectCollectionActiveWindow.php:144
Stack trace:
#0 C:\luyashopadmin\vendor\luyadev\luya-module-admin\src\aws\ImageSelectCollectionActiveWindow.php(202): luya\admin\aws\ImageSelectCollectionActiveWindow->getImageArray(223)
#1 [internal function]: luya\admin\aws\ImageSelectCollectionActiveWindow->callbackAddImageToIndex('62')
#2 C:\luyashopadmin\vendor\luyadev\luya-core\helpers\ObjectHelper.php(186): call_user_func_array(Array, Array)
#3 C:\luyashopadmin\vendor\luyadev\luya-module-admin\src\ngrest\render\RenderActiveWindowCallback.php(41): luya\helpers\ObjectHelper::callMethodSanitizeArguments(Object(luya\admin\aws\ImageSelectCollectionActiveWindow), 'callbackAddImag...', Array)
#4 C:\luyashopadmin\vendor\luyadev\luya-module-admin\src\ngrest\NgRest.php(55): luya\admin\ngrest\render\RenderActiveWindowCallback->render()
#5 C:\luyashopadmin\vendor\luyadev\luya-module-admin\src\ngrest\base\Api.php(750): luya\admin\ngrest\NgRest->render(Object(luya\admin\ngrest\render\RenderActiveWindowCallback))
#6 [internal function]: luya\admin\ngrest\base\Api->actionActiveWindowCallback()
#7 C:\luyashopadmin\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#8 C:\luyashopadmin\vendor\yiisoft\yii2\base\Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#9 C:\luyashopadmin\vendor\yiisoft\yii2\base\Module.php(552): yii\base\Controller->runAction('active-window-c...', Array)
#10 C:\luyashopadmin\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/api-galle...', Array)
#11 C:\luyashopadmin\vendor\luyadev\luya-core\web\Application.php(52): yii\web\Application->handleRequest(Object(luya\web\Request))
#12 C:\luyashopadmin\vendor\yiisoft\yii2\base\Application.php(384): luya\web\Application->handleRequest(Object(luya\web\Request))
#13 C:\luyashopadmin\vendor\luyadev\luya-core\base\Boot.php(251): yii\base\Application->run()
#14 C:\luyashopadmin\vendor\luyadev\luya-core\base\Boot.php(195): luya\base\Boot->applicationWeb()
#15 C:\luyashopadmin\public_html\index.php(8): luya\base\Boot->run()
#16 {main}

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
what luya version do you use?
